import PDFDocument from 'pdfkit';
import { Writable } from 'stream';

const ORANGE = '#EA580C';
const BLACK = '#0A0A0A';
const WHITE = '#FFFFFF';
const RED = '#DC2626';
const GRAY = '#888888';

export interface JobReport {
  sessionId: string;
  trade: string;
  jobAddress?: string | null;
  date: Date;
  summary: string;
  conditions: string[];
  workPerformed: string[];
  safetyAlerts: string[];
  codeRefs: string[];
  followUp: string[];
}

export function buildPdf(report: JobReport): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header ────────────────────────────────────────────────────────────
    doc.fontSize(28).font('Helvetica-Bold').fillColor(ORANGE).text('ACTOBER', { align: 'left' });
    doc.fontSize(11).font('Helvetica').fillColor(GRAY).text('Act on what you see.', { align: 'left' });
    doc.moveDown(0.5);

    doc.fontSize(10).fillColor(GRAY)
      .text(`Trade: ${report.trade}`, { continued: true })
      .text(`   |   Date: ${report.date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'left' });

    if (report.jobAddress) {
      doc.fontSize(12).font('Helvetica-Bold').fillColor(WHITE).text(report.jobAddress);
    }

    doc.moveTo(50, doc.y + 8).lineTo(560, doc.y + 8).strokeColor(ORANGE).lineWidth(1).stroke();
    doc.moveDown(1);

    // ── Summary ───────────────────────────────────────────────────────────
    sectionHeader(doc, 'SUMMARY');
    doc.fontSize(11).font('Helvetica').fillColor(WHITE).text(report.summary, { lineGap: 4 });
    doc.moveDown(1);

    // ── Conditions ────────────────────────────────────────────────────────
    if (report.conditions.length > 0) {
      sectionHeader(doc, 'CONDITIONS FOUND ON SITE');
      bulletList(doc, report.conditions, WHITE);
      doc.moveDown(1);
    }

    // ── Work Performed ────────────────────────────────────────────────────
    if (report.workPerformed.length > 0) {
      sectionHeader(doc, 'WORK PERFORMED');
      bulletList(doc, report.workPerformed, WHITE);
      doc.moveDown(1);
    }

    // ── Safety Alerts ─────────────────────────────────────────────────────
    if (report.safetyAlerts.length > 0) {
      sectionHeader(doc, 'SAFETY ALERTS', RED);
      bulletList(doc, report.safetyAlerts, RED);
      doc.moveDown(1);
    }

    // ── Code References ───────────────────────────────────────────────────
    if (report.codeRefs.length > 0) {
      sectionHeader(doc, 'CODE REFERENCES');
      bulletList(doc, report.codeRefs, WHITE);
      doc.moveDown(1);
    }

    // ── Follow-Up ─────────────────────────────────────────────────────────
    if (report.followUp.length > 0) {
      sectionHeader(doc, 'RECOMMENDED FOLLOW-UP');
      bulletList(doc, report.followUp, WHITE);
      doc.moveDown(1);
    }

    // ── Footer ────────────────────────────────────────────────────────────
    const pageBottom = doc.page.height - 40;
    doc.moveTo(50, pageBottom - 10).lineTo(560, pageBottom - 10).strokeColor(GRAY).lineWidth(0.5).stroke();
    doc.fontSize(8).font('Helvetica').fillColor(GRAY)
      .text(
        `Generated by Actober AI Coaching  •  actober.com  •  Session ${report.sessionId.slice(0, 8)}`,
        50,
        pageBottom,
        { align: 'center', width: 510 }
      );

    doc.end();
  });
}

function sectionHeader(doc: InstanceType<typeof PDFDocument>, title: string, color = ORANGE) {
  doc.fontSize(12).font('Helvetica-Bold').fillColor(color).text(title);
  doc.moveDown(0.3);
}

function bulletList(doc: InstanceType<typeof PDFDocument>, items: string[], color: string) {
  items.forEach((item) => {
    doc.fontSize(11).font('Helvetica').fillColor(color).text(`• ${item}`, { lineGap: 3, indent: 10 });
  });
}
